#!/bin/sh
CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' \
	-- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

image() {
	if [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y":"%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' \
			"$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
		exit 1
	else
		chafa "$1" -s "$4x"
	fi
}

batorcat() {
	file="$1"
	shift
	if command -v bat > /dev/null 2>&1; then
		bat --color=always --style=plain --pager=never "$file" "$@"
	else
		cat "$file"
	fi
}

glowormdcat() {
	file="$1"
	shift
	if command -v glow > /dev/null 2>&1; then
		lowdown -Tterm "$file"
	else
		mdcat "$file"
	fi
}

# TODO: Unimplemented stuff (Patches Welcome)
#	*.tar.bz2|*.tbz2) tar tjf "$1" ;;
#	*.tar.txz|*.txz) xz --list "$1" ;;
#	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" ;;
#	*.rar) unrar l "$1" ;;
#	*.md) glowormdcat "$1";;
#	*.7z) 7z l "$1" ;;
#	*.[1-8]) man "$1" | col -b | cat -v ;;
#	*.iso) iso-info --no-header -l "$1" ;;
#	
#	*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[ax]|
#	*.spx|*.opus|*.as[fx]|*.mka)
#	*.epub)
#	*.cbz|*.cbr|*.cbt)
#	*.avi|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg
#	|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
#	*.bmp|*.xpm|*.webp|*.jfif|*.ico
#
#	*.doc) catdoc "$1" ;;
#	*.xls|*.xlsx)
#	*.docx) docx2txt "$1" ;;
#	*.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
#

case "$(file -Lb -- "$1" | cut -d',' -f1)" in
	#Compression
	*POSIX\ tar*) tar tf "$1" ;;
	gzip*) gunzip -l "$1" ;;

	#Media
	HTML*) w3m -dump "$1" ;; 
	Ogg*) mediainfo "$1" | sed "s/\\s\\{15\\}//" ;;
	PNG*|JPG*|JPEG*|GIF*|TIFF*)
		image "$1" "$2" "$3" "$4" "$5" ;;
	PDF*)
		[ ! -f "${CACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5" ;;
	SVG*)
		[ ! -f "${CACHE}.jpg" ] && convert "$1" "${CACHE}.jpg"
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5" ;;
	ISO\ Media)
		[ ! -f "${CACHE}.jpg" ] && \
			ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5" 
		;;

	#Binarys
	*relocatable) nm "$1" ;;

	# Misc
	BitTorrent*) transmission-show "$1" ;;

	#Text & data
	*) file -ibL "$1" | grep -q "^text" && batorcat "$1" || file -Lb "$1" ;;
esac

exit 0
